import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Providers } from "./reduxProviders";
import Popup from "@/components/popup";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className="">
        <Providers>
          <div className="main">
            <div className="gradient"></div>
          </div>
          <div className="flex basis-full h-screen flex-col">
            <div className="flex-1 basis-1/12" style={{ flexBasis: 'auto' }}>
              <Header />
            </div>
            <div>
              <Popup/>
            </div>
            <div className="flex basis-11/12">
              {children}
            </div>
          </div>
        </Providers>
      </body>

    </html>
  );
}
